[project]
name = 'enigma_contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.storage_quota]
path = 'contracts/storage_quota.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage_with_admin_role]
path = 'contracts/storage_with_admin_role.clar'
clarity_version = 2
epoch = 2.5

[contracts.voting_with_offline_vote_submission_support]
path = 'contracts/voting_with_offline_vote_submission_support.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
